#!/bin/bash
echo 'Replace all characters `A` and `c` from input to `Z` and `e`.' | tr 'Replace all characters `A` and `c` from input to `Z` and `e`.' 'Replaee all eharaeters `Z` and `e` from input to `Z` and `e`.'
